### ISSUE TITLE
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.android.dx.command.dexer.Main$MainDexListFilter

### ISSUE THREAD

**Issue by sky-lijinbo** [sgwhp/openapm#3]
这个例子运行时 gradle console 会输出以下信息 好像没有成功

java.lang.RuntimeException: java.lang.ClassNotFoundException: com.android.dx.command.dexer.Main$MainDexListFilter
	at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source)
	at org.objectweb.asm.ClassWriter.a(Unknown Source)
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.github.sgwhp.openapm.agent.ClassTransformer.transform(ClassTransformer.java:35)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at com.github.sgwhp.openapm.agent.TransformAgent.premain(TransformAgent.java:65)
	at com.github.sgwhp.openapm.agent.TransformAgent.agentmain(TransformAgent.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)

**Comment by sgwhp** [comment]
IndexOutOfBoundsException堆栈有没打印出来，如果没有，是否修改了buildtools版本 #1

**Comment by sky-lijinbo** [comment]
哇塞，惊现大神,刚看了以下  堆栈信息已经打印出来,我再研究研究.

**Comment by sgwhp** [comment]
堆栈已打印说明是正常的
